```{r}
library(tidyverse)
diamonds <- read_csv('diamonds.csv')
diamonds
str(diamonds$cut)

```
```{r}
#1.1
library(ggplot2)
ggplot(diamonds, aes(x=carat, y=price)) + geom_point()
```
```{r}
#1.2
ggplot(diamonds, aes(x=carat, y=price, color=clarity)) + geom_point() + ggtitle("Carat vs Price")
#1.3
```


```{r}
#2.1
ggplot(diamonds, aes(x=price)) + geom_histogram(colour = 4, fill = "white", bins = 40)
```
```{r}
#2.2
ggplot(diamonds, aes(x=price)) + geom_histogram(colour = 4, fill = "white", bins = 40)+ scale_x_log10()
```
```{r}
#3.1
ggplot(diamonds, aes(x=cut,y=price)) + geom_boxplot()+scale_y_log10()
```
```{r}
#3.2
ggplot(diamonds, aes(x=cut,y=price,fill=cut)) + geom_boxplot()+scale_y_log10()
```

```{r}
#4.1
filtered_price <- diamonds %>%
  filter(price>1000) %>%
  filter(cut %in% c("Good","Ideal","Premium"))
filtered_price
```


```{r}
#4.2
ggplot(filtered_price, aes(x=cut, y=depth)) + geom_bar(stat="identity")
```
```{r}
#4.3
ggplot(filtered_price, aes(x=cut, y=depth)) + geom_bar(stat="identity") + facet_wrap(~ clarity)
```

```{r}
#4.4
ggplot(filtered_price, aes(x=cut, y=depth, fill=clarity)) + geom_bar(stat="identity") + facet_wrap(~ clarity) 
```
```{r}
#1.
median_dimension_diamond <- diamonds %>%
  summarize(mediaX = mean(x), mediaY=mean(y), mediaZ = mean(z))
median_dimension_diamond
  
```
```{r}
median_dimension_diamond <- diamonds %>%
  summarize(mediaX = mean(x), mediaY=mean(y), mediaZ = mean(z))
median_dimension_diamond
```

```{r}
#2.
cut_premium <- diamonds %>%
  filter(cut=="Premium") %>%
  group_by(clarity) %>%
  summarize(minPrice = mean(price), maxPrice=mean(price))
cut_premium
```
```{r}
#3.
ggplot(cut_premium, aes(x=clarity, y=maxPrice, fill=cl)) + geom_bar(stat="identity")
```

